### ISSUE TITLE
非推奨とされている設定ウィンドウを無くす?

### ISSUE THREAD

**Issue by Sayamame-beans** [Azukimochi/LightLimitChangerForMA#134]
`Tools/Modular Avatar/LightLimitChanger`のウィンドウは https://github.com/Azukimochi/LightLimitChangerForMA/pull/23 で非推奨とされてから半年ほど経過しているため、廃止にしても良いかもしれないと思いました。

**Comment by Azukimochi** [comment]
確かにそうですね。いつの間にか半年も時間が経っていたとは…。
次ちょうどマイナーバージョンアップの予定なのでこの際削除の方向でいきたいと思います

**Comment by Azukimochi** [comment]
10f41e793a3a41846d2370d1522dad7f2d989b90　にて完了
