### ISSUE TITLE
macOSで色温度または彩度を有効にすると衣装の一部のマテリアルの色がおかしくなった

### ISSUE THREAD

**Issue by enitimeago** [Azukimochi/LightLimitChangerForMA#151]
windowsで問題ないですがmac(arm64)+unity2019、2022で再現できた

lilToon 1.7.3, LightLimitChanger 1.11.3

現在LLCのみ入っているプロジェクトにはまだ試していないので他のツールの影響があるかどうかわかりません

<img width="1508" alt="Screenshot 2024-04-17 at 01 19 42" src="https://github.com/Azukimochi/LightLimitChangerForMA/assets/129673786/96c8e7a0-770b-4a0d-aee8-1343b98f99eb">

**Comment by enitimeago** [comment]
明度とガンマの値が原因な気がします

`textureBaker.HSVG`が設定されないと問題が発生しないことを確認しました

<img width="1138" alt="Screenshot 2024-04-17 at 22 41 08" src="https://github.com/Azukimochi/LightLimitChangerForMA/assets/129673786/e5266e01-6ca4-4330-a093-674782857bef">

**Comment by enitimeago** [comment]
lilToonの`lilToonInspector#RunBake`とLightLimitChangerの`TextureBaker#Bake`を調査したところ原因がわかりました

LightLimitChangerはAsyncGPUReadbackを使用していますが、`lilToonInspector#RunBake`の方はAsyncGPUReadbackではなく`Texture2D#ReadPixels`を使用しています

LightLimitChangerをAsyncGPUReadbackから`Texture2D#ReadPixels`に変更したところ色がおかしくなる問題が修正されていたようです

AsyncGPUReadbackとTexture2D#ReadPixelsの比較差はあまりよくわからないが、AsyncGPUReadbackを続けて使用する場合は、宛先のテクスチャと同じTextureFormatを明示的に設定する(つまり`TextureFormat.RGBA32`)必要があるようです

`AsyncGPUReadback#Request`のドキュメンテーション：
> **dstFormat** Target TextureFormat of the data. If the target format is different from the format stored on the GPU, **the conversion is automatic.**

pull requestを送ります

**Comment by Azukimochi** [comment]
原因の追求から解決まで本当にありがとうございます....！！
