### ISSUE TITLE
exclude .git folder from package zip

### ISSUE THREAD

**Issue by Misaka-L** [Azukimochi/LightLimitChangerForMA#203]
The vpm package zip contains the `.git` folder, which it should be exclude from package.

This problem have trouble me and other users who using git and it just make the package size become larger.

**Comment by Misaka-L** [comment]
I sae the commit: https://github.com/Azukimochi/LightLimitChangerForMA/commit/2d7b1221b8c1f536e45e9b2035a3289e17c5e3e8

but the `.git` folder was still contains in the latest release

**Comment by Azukimochi** [comment]
The .git file was certainly unnecessary.
Thank you for adding the excluded files and updating the actions.
