### ISSUE TITLE
v1.31.1-rc.1 can't work

### ISSUE THREAD

**Issue by yelandiealma** [Azukimochi/LightLimitChangerForMA#208]
[LLC1.13.1-rc.1 bug.txt](https://github.com/user-attachments/files/16412146/LLC1.13.1-rc.1.bug.txt)
https://anatawa12.github.io/ConsoleLogSaver/

**Comment by Azukimochi** [comment]
#203 の変更でAssembly Definitionも消えてしまったことで問題が発生しているようです

**Comment by Azukimochi** [comment]
fix #211 
Thanks for reporting !!
