### ISSUE TITLE
LLCが非アクティブ状態のときにMonochrome値をマテリアルの値に設定

### ISSUE THREAD

**Issue by noridev** [Azukimochi/LightLimitChangerForMA#227]
今のLLCは、非アクティブ状態のときにMonochromeおよびMonochrome Additive（Poiyomiのみ）の値を無条件に0に設定するようになっており、任意にマテリアルで値を設定した場合も無視しています。

ですからLLCをオンにしないと照明の色をそのまま受けるのでマテリアルにMonochrome値を設定した状態でも赤い照明は赤く、黄色い照明は黄色く見えるようになります。

**Comment by Azukimochi** [comment]
この挙動はかなり見落としに近いものだったので助かりました🙏
