### ISSUE TITLE
特定のテクスチャをベイクしようとすると失敗する？

### ISSUE THREAD

**Issue by GrabacrScarlet** [Azukimochi/LightLimitChangerForMA#27]
#25 の修正中に発覚したバグであんまり調査できてないのですが
- [EyePointer](https://booth.pm/ja/items/4742883)のマテリアルをベイクしようとすると焼きこみ時にエラーが起きる
  - 具体的には`AsyncGPUReadback`の結果が空っぽで新規テクスチャ生成に失敗する
- マテリアルのメインテクスチャを変えるとエラーは発生しない
  - なので原因は最初から入ってるテクスチャ？
 
もうちょっと調査が必要そう・・・

**Comment by AshleyScarlet** [comment]
たぶん1x1ピクセルのテクスチャだと死ぬ
解決法は、無い・・・

**Comment by AshleyScarlet** [comment]
解決した🥺
