### ISSUE TITLE
除外設定にプレハブを対応させる？

### ISSUE THREAD

**Issue by Rerigferl** [Azukimochi/LightLimitChangerForMA#58]
除外設定、現状SMRとマテリアルを入れるために型をObjectにしていたので何でも入ってしまう
その結果、Projectウィンドウからプレハブを投げ込んでしまっている人が居た

想定外の使い方ではあるけど、プレハブを除外設定に投げ込むのは結構使い道が良さそうなので、対応させちゃうのも良さそう
（全然弾くようにしても良いと思う）

**Comment by Sayamame-beans** [comment]
何らかのGameObjectを指定したときに、その子にあるもの全てが除外される、とかは助かる場面もありそうです(ギミック単位で除外したいときなど)

**Comment by Rerigferl** [comment]
プレハブの対応はムリそうだなあって長らく放置してましたが子の除外とかは良さそうですね
一旦このIssue閉じて立て直します 🙏
