### ISSUE TITLE
Re: liltoonのメインカラーが透過カラーである場合に不透明度が100にベイクされる

### ISSUE THREAD

**Issue by Narazaka** [Azukimochi/LightLimitChangerForMA#89]
#84 閉じられたが、1.7.10にしても相変わらず不透明度100に焼き込まれる

liltoon 1.4.1の「半透明（Hidden/lilToonTransparent）」、「[高負荷]屈折ぼかし（lilToonRefractionBlur）」にて確認

**Comment by Narazaka** [comment]
「色温度調整」のチェックを付けたLightLimitChangerプレハブを付けたアバターをAvatar3.0 Emulator ControlをONにした状態で動かしたときにこの挙動になるようです。

[llc.zip](https://github.com/Azukimochi/LightLimitChangerForMA/files/13508582/llc.zip)
最小で再現するunitpackageです。LightLimitChanger 1.7.10とAV3Emulator 3.2.4で動きます。

**Comment by AshleyScarlet** [comment]
アニメーションでアルファを１に固定していたのが原因でした。

SkinnedMeshRenderer単位でしかアニメーションを生成できないUnity固有の問題となるので、アニメーション生成の改良ではなく、ベイク時にアルファ値を含めたテクスチャを生成することで回避します。
